import { HighlightStyle } from '@codemirror/language'
import { tags } from '@lezer/highlight'

/** CSS classes applied to Markdown tokens in the source editor. */
export const markdownTokenClasses = [
  'cm-md-heading',
  'cm-md-em',
  'cm-md-strong',
  'cm-md-strike',
  'cm-md-link',
  'cm-md-code',
  'cm-md-quote',
  'cm-md-comment',
  'cm-md-mark',
] as const

/** Class-based Markdown highlighting; colors come from theme CSS variables. */
export const markdownHighlightStyle = HighlightStyle.define([
  { tag: tags.heading1, class: 'cm-md-heading' },
  { tag: tags.heading2, class: 'cm-md-heading' },
  { tag: tags.heading3, class: 'cm-md-heading' },
  { tag: tags.heading4, class: 'cm-md-heading' },
  { tag: tags.heading5, class: 'cm-md-heading' },
  { tag: tags.heading6, class: 'cm-md-heading' },
  { tag: tags.heading, class: 'cm-md-heading' },
  { tag: tags.emphasis, class: 'cm-md-em' },
  { tag: tags.strong, class: 'cm-md-strong' },
  { tag: tags.strikethrough, class: 'cm-md-strike' },
  { tag: tags.link, class: 'cm-md-link' },
  { tag: tags.labelName, class: 'cm-md-link' },
  { tag: tags.monospace, class: 'cm-md-code' },
  { tag: tags.quote, class: 'cm-md-quote' },
  { tag: tags.comment, class: 'cm-md-comment' },
  { tag: tags.url, class: 'cm-md-mark' },
  { tag: tags.processingInstruction, class: 'cm-md-mark' },
  { tag: tags.meta, class: 'cm-md-mark' },
  { tag: tags.punctuation, class: 'cm-md-mark' },
  { tag: tags.escape, class: 'cm-md-mark' },
  { tag: tags.list, class: 'cm-md-mark' },
  { tag: tags.contentSeparator, class: 'cm-md-mark' },
  { tag: tags.atom, class: 'cm-md-mark' },
  { tag: tags.character, class: 'cm-md-mark' },
  { tag: tags.string, class: 'cm-md-mark' },
])

/** CSS classes applied to source-language tokens in the editor. */
export const codeTokenClasses = [
  'cm-code-kw',
  'cm-code-str',
  'cm-code-num',
  'cm-code-com',
  'cm-code-fn',
  'cm-code-type',
  'cm-code-prop',
  'cm-code-name',
  'cm-code-punct',
] as const

/** Class-based source highlighting; colors come from theme CSS variables. */
export const codeHighlightStyle = HighlightStyle.define([
  { tag: tags.keyword, class: 'cm-code-kw' },
  { tag: tags.moduleKeyword, class: 'cm-code-kw' },
  { tag: tags.definitionKeyword, class: 'cm-code-kw' },
  { tag: tags.controlKeyword, class: 'cm-code-kw' },
  { tag: tags.operatorKeyword, class: 'cm-code-kw' },
  { tag: tags.modifier, class: 'cm-code-kw' },
  { tag: tags.self, class: 'cm-code-kw' },
  { tag: tags.atom, class: 'cm-code-kw' },
  { tag: tags.bool, class: 'cm-code-kw' },
  { tag: tags.null, class: 'cm-code-kw' },
  { tag: tags.string, class: 'cm-code-str' },
  { tag: tags.special(tags.string), class: 'cm-code-str' },
  { tag: tags.character, class: 'cm-code-str' },
  { tag: tags.regexp, class: 'cm-code-str' },
  { tag: tags.escape, class: 'cm-code-str' },
  { tag: tags.number, class: 'cm-code-num' },
  { tag: tags.integer, class: 'cm-code-num' },
  { tag: tags.float, class: 'cm-code-num' },
  { tag: tags.comment, class: 'cm-code-com' },
  { tag: tags.lineComment, class: 'cm-code-com' },
  { tag: tags.blockComment, class: 'cm-code-com' },
  { tag: tags.docComment, class: 'cm-code-com' },
  { tag: tags.function(tags.variableName), class: 'cm-code-fn' },
  { tag: tags.function(tags.propertyName), class: 'cm-code-fn' },
  { tag: tags.macroName, class: 'cm-code-fn' },
  { tag: tags.typeName, class: 'cm-code-type' },
  { tag: tags.className, class: 'cm-code-type' },
  { tag: tags.namespace, class: 'cm-code-type' },
  { tag: tags.standard(tags.typeName), class: 'cm-code-type' },
  { tag: tags.propertyName, class: 'cm-code-prop' },
  { tag: tags.attributeName, class: 'cm-code-prop' },
  { tag: tags.tagName, class: 'cm-code-type' },
  { tag: tags.variableName, class: 'cm-code-name' },
  { tag: tags.constant(tags.variableName), class: 'cm-code-name' },
  { tag: tags.labelName, class: 'cm-code-name' },
  { tag: tags.operator, class: 'cm-code-punct' },
  { tag: tags.punctuation, class: 'cm-code-punct' },
  { tag: tags.bracket, class: 'cm-code-punct' },
  { tag: tags.angleBracket, class: 'cm-code-punct' },
  { tag: tags.squareBracket, class: 'cm-code-punct' },
  { tag: tags.paren, class: 'cm-code-punct' },
  { tag: tags.brace, class: 'cm-code-punct' },
  { tag: tags.separator, class: 'cm-code-punct' },
  { tag: tags.derefOperator, class: 'cm-code-punct' },
  { tag: tags.meta, class: 'cm-code-punct' },
  { tag: tags.processingInstruction, class: 'cm-code-punct' },
])
